name: Keep Backend Alive

on:
  schedule:
    # Se ejecuta cada 30 minutos
    - cron: "*/30 * * * *"
  workflow_dispatch: # Permite activarlo manualmente desde GitHub si quisieras

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        # Usamos curl para hacer una petición simple a tu API
        # El flag -I pide solo los encabezados (es más rápido y ligero)
        run: curl -I https://paola-deco-api.onrender.com/api/services
